platform :ios, '8.0'
use_frameworks!
target 'Photos' do
	 pod 'Alamofire', '~> 3.0'
         pod 'ObjectMapper', '~> 1.5'
         pod 'SwiftyJSON'
	 pod 'RxSwift'
	 pod 'RxCocoa'
	 pod 'LNRSimpleNotifications', '~> 0.4.2'
	 pod 'BusyNavigationBar', '~> 1.1.0'
	 pod 'UIImageColors', '~> 1.0.0'
	 pod 'PINRemoteImage'
	 pod 'HanekeSwift', '~> 0.10.1'
target 'PhotosTests' do
    inherit! :search_paths
    	pod 'RxSwift'
	pod 'RxTests'  
  end

  target 'PhotosUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
