platform :ios, '9.0'
use_frameworks!
target 'Photos' do
	 pod 'Alamofire', '~> 3.0'
         pod 'ObjectMapper', '~> 1.5'
         pod 'SwiftyJSON'
	 pod 'RxSwift'
	 pod 'RxCocoa'
target 'PhotosTests' do
    inherit! :search_paths
    	pod 'RxSwift'
	pod 'RxTests'  
  end

  target 'PhotosUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
